### ISSUE TITLE
Work on Save progress feature

### ISSUE THREAD

**Issue by Mayalynn96** [claricetran/dont-wake-up#62]
- [x] disable save button when in mini Game
- [x] make player health set to 100% when player needs to restart mini game
- [x] make player stats save on save press
- [x] make story progression checkpoint save
- [x] make sure everything populates properly on page load
- [x] make game save when won or delete game when name is submited

**Comment by claricetran** [comment]
-[ ] Add in score save functionality after we figure out how it should be calculated
